service:
  name: todo

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpacking: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws

functions:
  createTodos:
    handler: src/functions/createTodos.handle
    events:
      - http:
          path: /todo/{userid}
          method: POST
          cors: true

  listTodos:
    handler: src/functions/listTodos.handle
    events:
      - http:
          path: /todo/{userid}
          method: GET
          cors: true

resources:
  Resources:
    dbTodo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
